//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BP커미션정책
    {
        public long 정책번호 { get; set; }
        public string 행사년도 { get; set; }
        public string 행사분기 { get; set; }
        public System.DateTime 출발일시작 { get; set; }
        public System.DateTime 출발일종료 { get; set; }
        public string BP분류 { get; set; }
        public string BP등급 { get; set; }
        public decimal 상품커미션율 { get; set; }
        public decimal 클럽커미션율 { get; set; }
    }
}
