//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JW_주문
    {
        public int 주문번호 { get; set; }
        public int 주문일련번호 { get; set; }
        public System.DateTime 주문일 { get; set; }
        public string 주문구분코드 { get; set; }
        public Nullable<decimal> GROSS { get; set; }
        public Nullable<decimal> COMM { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> CHARGE { get; set; }
        public string 취소 { get; set; }
        public long 단체번호 { get; set; }
        public Nullable<System.DateTime> 출발일 { get; set; }
    }
}
