//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JW_키테스트0529
    {
        public string 단체번호 { get; set; }
        public long 단체일련번호 { get; set; }
        public string 단체구분코드 { get; set; }
        public System.DateTime 출발일 { get; set; }
        public string 상품코드 { get; set; }
        public string 항공코드 { get; set; }
        public System.DateTime 등록일 { get; set; }
    }
}
