//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_MDS
    {
        public System.DateTime LogDT { get; set; }
        public int LogID { get; set; }
        public string LogRoute { get; set; }
        public string AppName { get; set; }
        public string AppVer { get; set; }
        public string HostName { get; set; }
        public string HostIP { get; set; }
        public System.DateTime HostStartDT { get; set; }
        public System.DateTime HostEndDT { get; set; }
        public Nullable<decimal> LeadSecond { get; set; }
        public string LeadHHMMSS { get; set; }
        public int UserID { get; set; }
        public string ClientUserIP { get; set; }
        public string CallerPath { get; set; }
        public string CallerMember { get; set; }
        public string CallerLine { get; set; }
        public string DB_Target { get; set; }
        public string SQL { get; set; }
        public string MdsParameter { get; set; }
        public string Exception { get; set; }
        public string LogSeq { get; set; }
        public string MdsVer { get; set; }
        public string ProcessID { get; set; }
        public string MdsMethod { get; set; }
    }
}
