//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class M6Entities : DbContext
    {
        public M6Entities()
            : base("name=M6Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DDLHistory> DDLHistories { get; set; }
        public virtual DbSet<JW_주문> JW_주문 { get; set; }
        public virtual DbSet<JW_키테스트0529> JW_키테스트0529 { get; set; }
        public virtual DbSet<LOG_MDS> LOG_MDS { get; set; }
        public virtual DbSet<MSync_FileList> MSync_FileList { get; set; }
        public virtual DbSet<가격모델> 가격모델 { get; set; }
        public virtual DbSet<개체> 개체 { get; set; }
        public virtual DbSet<개체관계> 개체관계 { get; set; }
        public virtual DbSet<거래처> 거래처 { get; set; }
        public virtual DbSet<거래처_담당배정> 거래처_담당배정 { get; set; }
        public virtual DbSet<거래처담당> 거래처담당 { get; set; }
        public virtual DbSet<거래처분류> 거래처분류 { get; set; }
        public virtual DbSet<거래처직원> 거래처직원 { get; set; }
        public virtual DbSet<거래처첨부파일> 거래처첨부파일 { get; set; }
        public virtual DbSet<검색태그> 검색태그 { get; set; }
        public virtual DbSet<공급계약> 공급계약 { get; set; }
        public virtual DbSet<공유> 공유 { get; set; }
        public virtual DbSet<공항> 공항 { get; set; }
        public virtual DbSet<구독> 구독 { get; set; }
        public virtual DbSet<구매내역> 구매내역 { get; set; }
        public virtual DbSet<구매주문> 구매주문 { get; set; }
        public virtual DbSet<구매첨부파일> 구매첨부파일 { get; set; }
        public virtual DbSet<국가> 국가 { get; set; }
        public virtual DbSet<국내도로명주소> 국내도로명주소 { get; set; }
        public virtual DbSet<국내지번주소> 국내지번주소 { get; set; }
        public virtual DbSet<그룹발권요청> 그룹발권요청 { get; set; }
        public virtual DbSet<기초코드> 기초코드 { get; set; }
        public virtual DbSet<기획전_구역> 기획전_구역 { get; set; }
        public virtual DbSet<기획전_카달로그> 기획전_카달로그 { get; set; }
        public virtual DbSet<단체이동이력> 단체이동이력 { get; set; }
        public virtual DbSet<단체프로모션> 단체프로모션 { get; set; }
        public virtual DbSet<닷컴구역> 닷컴구역 { get; set; }
        public virtual DbSet<닷컴구역_특선상품> 닷컴구역_특선상품 { get; set; }
        public virtual DbSet<댓글> 댓글 { get; set; }
        public virtual DbSet<도시> 도시 { get; set; }
        public virtual DbSet<리뷰> 리뷰 { get; set; }
        public virtual DbSet<마일리지합산대상자> 마일리지합산대상자 { get; set; }
        public virtual DbSet<마일리지합산신청> 마일리지합산신청 { get; set; }
        public virtual DbSet<마일리지합산증빙서류> 마일리지합산증빙서류 { get; set; }
        public virtual DbSet<마일리지합산해지> 마일리지합산해지 { get; set; }
        public virtual DbSet<메세지이력> 메세지이력 { get; set; }
        public virtual DbSet<메세지정책> 메세지정책 { get; set; }
        public virtual DbSet<부가서비스> 부가서비스 { get; set; }
        public virtual DbSet<부서> 부서 { get; set; }
        public virtual DbSet<브랜드> 브랜드 { get; set; }
        public virtual DbSet<비고> 비고 { get; set; }
        public virtual DbSet<빌링_ACDM> 빌링_ACDM { get; set; }
        public virtual DbSet<빌링_계산서> 빌링_계산서 { get; set; }
        public virtual DbSet<빌링_리펀드> 빌링_리펀드 { get; set; }
        public virtual DbSet<빌링_티켓> 빌링_티켓 { get; set; }
        public virtual DbSet<빌링_합계> 빌링_합계 { get; set; }
        public virtual DbSet<사용자_단축키> 사용자_단축키 { get; set; }
        public virtual DbSet<사용자_레이아웃> 사용자_레이아웃 { get; set; }
        public virtual DbSet<사용자_리본_빠른실행> 사용자_리본_빠른실행 { get; set; }
        public virtual DbSet<사용자_스킨> 사용자_스킨 { get; set; }
        public virtual DbSet<사용자_자동시작> 사용자_자동시작 { get; set; }
        public virtual DbSet<사용자_환경설정> 사용자_환경설정 { get; set; }
        public virtual DbSet<사원_SYNC> 사원_SYNC { get; set; }
        public virtual DbSet<상품> 상품 { get; set; }
        public virtual DbSet<상품가격> 상품가격 { get; set; }
        public virtual DbSet<상품가격옵션> 상품가격옵션 { get; set; }
        public virtual DbSet<상품견적> 상품견적 { get; set; }
        public virtual DbSet<상품그룹_구역> 상품그룹_구역 { get; set; }
        public virtual DbSet<상품단체> 상품단체 { get; set; }
        public virtual DbSet<상품단체가이드> 상품단체가이드 { get; set; }
        public virtual DbSet<상품단체담당> 상품단체담당 { get; set; }
        public virtual DbSet<상품단체일정> 상품단체일정 { get; set; }
        public virtual DbSet<상품담당> 상품담당 { get; set; }
        public virtual DbSet<상품메세지> 상품메세지 { get; set; }
        public virtual DbSet<상품부가서비스> 상품부가서비스 { get; set; }
        public virtual DbSet<상품비고마스터> 상품비고마스터 { get; set; }
        public virtual DbSet<상품시즌날짜> 상품시즌날짜 { get; set; }
        public virtual DbSet<상품시즌상세> 상품시즌상세 { get; set; }
        public virtual DbSet<상품시즌정책> 상품시즌정책 { get; set; }
        public virtual DbSet<상품여정> 상품여정 { get; set; }
        public virtual DbSet<상품옵션> 상품옵션 { get; set; }
        public virtual DbSet<상품원가표> 상품원가표 { get; set; }
        public virtual DbSet<상품일정> 상품일정 { get; set; }
        public virtual DbSet<상품일정요약> 상품일정요약 { get; set; }
        public virtual DbSet<상품입찰> 상품입찰 { get; set; }
        public virtual DbSet<상품입찰설정> 상품입찰설정 { get; set; }
        public virtual DbSet<상품재고> 상품재고 { get; set; }
        public virtual DbSet<상품재고반납> 상품재고반납 { get; set; }
        public virtual DbSet<상품재고세부> 상품재고세부 { get; set; }
        public virtual DbSet<상품재고여정> 상품재고여정 { get; set; }
        public virtual DbSet<상품재고일정> 상품재고일정 { get; set; }
        public virtual DbSet<상품재고입고> 상품재고입고 { get; set; }
        public virtual DbSet<상품정보> 상품정보 { get; set; }
        public virtual DbSet<상품정보템플릿> 상품정보템플릿 { get; set; }
        public virtual DbSet<상품제휴가격> 상품제휴가격 { get; set; }
        public virtual DbSet<상품조건> 상품조건 { get; set; }
        public virtual DbSet<상품지역> 상품지역 { get; set; }
        public virtual DbSet<상품지역브랜드> 상품지역브랜드 { get; set; }
        public virtual DbSet<상품취소료규정> 상품취소료규정 { get; set; }
        public virtual DbSet<상품카달로그> 상품카달로그 { get; set; }
        public virtual DbSet<상품카달로그매핑> 상품카달로그매핑 { get; set; }
        public virtual DbSet<상품카테고리> 상품카테고리 { get; set; }
        public virtual DbSet<상품태그> 상품태그 { get; set; }
        public virtual DbSet<서버> 서버 { get; set; }
        public virtual DbSet<선급계약> 선급계약 { get; set; }
        public virtual DbSet<선급보증금> 선급보증금 { get; set; }
        public virtual DbSet<세금계산서> 세금계산서 { get; set; }
        public virtual DbSet<센딩> 센딩 { get; set; }
        public virtual DbSet<숙박재고> 숙박재고 { get; set; }
        public virtual DbSet<아이템담당> 아이템담당 { get; set; }
        public virtual DbSet<아이템담당배정> 아이템담당배정 { get; set; }
        public virtual DbSet<알림> 알림 { get; set; }
        public virtual DbSet<여행자보험료> 여행자보험료 { get; set; }
        public virtual DbSet<연락처> 연락처 { get; set; }
        public virtual DbSet<웹구역> 웹구역 { get; set; }
        public virtual DbSet<웹기획전> 웹기획전 { get; set; }
        public virtual DbSet<웹사이트> 웹사이트 { get; set; }
        public virtual DbSet<웹이벤트구역> 웹이벤트구역 { get; set; }
        public virtual DbSet<웹컨텐츠> 웹컨텐츠 { get; set; }
        public virtual DbSet<웹페이지> 웹페이지 { get; set; }
        public virtual DbSet<유료센딩> 유료센딩 { get; set; }
        public virtual DbSet<은행계좌> 은행계좌 { get; set; }
        public virtual DbSet<인센티브견적> 인센티브견적 { get; set; }
        public virtual DbSet<인센티브단체> 인센티브단체 { get; set; }
        public virtual DbSet<인센티브일정> 인센티브일정 { get; set; }
        public virtual DbSet<인센티브일정요약> 인센티브일정요약 { get; set; }
        public virtual DbSet<인센티브입찰> 인센티브입찰 { get; set; }
        public virtual DbSet<인센티브추가항목> 인센티브추가항목 { get; set; }
        public virtual DbSet<일정계획> 일정계획 { get; set; }
        public virtual DbSet<일정계획세부> 일정계획세부 { get; set; }
        public virtual DbSet<장소> 장소 { get; set; }
        public virtual DbSet<장소이미지> 장소이미지 { get; set; }
        public virtual DbSet<재고반납> 재고반납 { get; set; }
        public virtual DbSet<저작권> 저작권 { get; set; }
        public virtual DbSet<정산> 정산 { get; set; }
        public virtual DbSet<주문담당> 주문담당 { get; set; }
        public virtual DbSet<주문아이템> 주문아이템 { get; set; }
        public virtual DbSet<주문필드값> 주문필드값 { get; set; }
        public virtual DbSet<지방> 지방 { get; set; }
        public virtual DbSet<지상비견적> 지상비견적 { get; set; }
        public virtual DbSet<지상비견적세부> 지상비견적세부 { get; set; }
        public virtual DbSet<지상비견적숙박변경> 지상비견적숙박변경 { get; set; }
        public virtual DbSet<지상비견적업체> 지상비견적업체 { get; set; }
        public virtual DbSet<지상비견적조정> 지상비견적조정 { get; set; }
        public virtual DbSet<지상비수의계약> 지상비수의계약 { get; set; }
        public virtual DbSet<지상비입찰> 지상비입찰 { get; set; }
        public virtual DbSet<지상비입찰상품> 지상비입찰상품 { get; set; }
        public virtual DbSet<지상비입찰숙박변경> 지상비입찰숙박변경 { get; set; }
        public virtual DbSet<직원권한> 직원권한 { get; set; }
        public virtual DbSet<첨부파일> 첨부파일 { get; set; }
        public virtual DbSet<카달로그> 카달로그 { get; set; }
        public virtual DbSet<카테고리> 카테고리 { get; set; }
        public virtual DbSet<캠페인> 캠페인 { get; set; }
        public virtual DbSet<컨텐츠파일> 컨텐츠파일 { get; set; }
        public virtual DbSet<테스트0528> 테스트0528 { get; set; }
        public virtual DbSet<통화> 통화 { get; set; }
        public virtual DbSet<특선상품> 특선상품 { get; set; }
        public virtual DbSet<특선상품_구역> 특선상품_구역 { get; set; }
        public virtual DbSet<특선상품세부> 특선상품세부 { get; set; }
        public virtual DbSet<티켓> 티켓 { get; set; }
        public virtual DbSet<티켓_DSR> 티켓_DSR { get; set; }
        public virtual DbSet<티켓_발권수수료> 티켓_발권수수료 { get; set; }
        public virtual DbSet<티켓매핑> 티켓매핑 { get; set; }
        public virtual DbSet<티켓재고> 티켓재고 { get; set; }
        public virtual DbSet<판매_증빙> 판매_증빙 { get; set; }
        public virtual DbSet<판매가격세부> 판매가격세부 { get; set; }
        public virtual DbSet<판매고객> 판매고객 { get; set; }
        public virtual DbSet<판매명세> 판매명세 { get; set; }
        public virtual DbSet<판매세부> 판매세부 { get; set; }
        public virtual DbSet<판매수납> 판매수납 { get; set; }
        public virtual DbSet<판매아이템> 판매아이템 { get; set; }
        public virtual DbSet<판매업체세부> 판매업체세부 { get; set; }
        public virtual DbSet<판매제휴그룹> 판매제휴그룹 { get; set; }
        public virtual DbSet<판매주문> 판매주문 { get; set; }
        public virtual DbSet<판매주문_배송> 판매주문_배송 { get; set; }
        public virtual DbSet<판매주문결제요청> 판매주문결제요청 { get; set; }
        public virtual DbSet<판매주문수납> 판매주문수납 { get; set; }
        public virtual DbSet<판매주문외부> 판매주문외부 { get; set; }
        public virtual DbSet<판매주문외부결제> 판매주문외부결제 { get; set; }
        public virtual DbSet<판매주문외부연동> 판매주문외부연동 { get; set; }
        public virtual DbSet<판매주문작업메모> 판매주문작업메모 { get; set; }
        public virtual DbSet<판매주문작업요청> 판매주문작업요청 { get; set; }
        public virtual DbSet<판매커미션> 판매커미션 { get; set; }
        public virtual DbSet<프로그램> 프로그램 { get; set; }
        public virtual DbSet<프로그램권한> 프로그램권한 { get; set; }
        public virtual DbSet<프로모션> 프로모션 { get; set; }
        public virtual DbSet<프로모션단체> 프로모션단체 { get; set; }
        public virtual DbSet<프로젝트플랜> 프로젝트플랜 { get; set; }
        public virtual DbSet<필드> 필드 { get; set; }
        public virtual DbSet<항공사> 항공사 { get; set; }
        public virtual DbSet<행사단체> 행사단체 { get; set; }
        public virtual DbSet<행사단체일정> 행사단체일정 { get; set; }
        public virtual DbSet<행사단체조인> 행사단체조인 { get; set; }
        public virtual DbSet<행사담당> 행사담당 { get; set; }
        public virtual DbSet<회계계정> 회계계정 { get; set; }
        public virtual DbSet<회계미수유예> 회계미수유예 { get; set; }
        public virtual DbSet<회계분개> 회계분개 { get; set; }
        public virtual DbSet<회계이월> 회계이월 { get; set; }
        public virtual DbSet<회계전표> 회계전표 { get; set; }
        public virtual DbSet<회원> 회원 { get; set; }
        public virtual DbSet<회원활동이력> 회원활동이력 { get; set; }
        public virtual DbSet<BP커미션정책> BP커미션정책 { get; set; }
        public virtual DbSet<COPY> COPies { get; set; }
        public virtual DbSet<JSON> JSONs { get; set; }
        public virtual DbSet<거래처닷컴배분> 거래처닷컴배분 { get; set; }
        public virtual DbSet<국가_출입국안내> 국가_출입국안내 { get; set; }
        public virtual DbSet<메세지템플릿> 메세지템플릿 { get; set; }
        public virtual DbSet<메타정보> 메타정보 { get; set; }
        public virtual DbSet<부서경로> 부서경로 { get; set; }
        public virtual DbSet<브랜드가격정책> 브랜드가격정책 { get; set; }
        public virtual DbSet<비자> 비자 { get; set; }
        public virtual DbSet<사원> 사원 { get; set; }
        public virtual DbSet<상품단체원가> 상품단체원가 { get; set; }
        public virtual DbSet<상품선택관광> 상품선택관광 { get; set; }
        public virtual DbSet<상품재고상세> 상품재고상세 { get; set; }
        public virtual DbSet<상품주문필드> 상품주문필드 { get; set; }
        public virtual DbSet<상품필드값> 상품필드값 { get; set; }
        public virtual DbSet<업무보조> 업무보조 { get; set; }
        public virtual DbSet<인센티브댓글> 인센티브댓글 { get; set; }
        public virtual DbSet<정산내역> 정산내역 { get; set; }
        public virtual DbSet<지상비입찰시즌> 지상비입찰시즌 { get; set; }
        public virtual DbSet<카드가맹> 카드가맹 { get; set; }
        public virtual DbSet<통장입금> 통장입금 { get; set; }
        public virtual DbSet<특선상품요약> 특선상품요약 { get; set; }
        public virtual DbSet<티켓_발권수수료_은행입금> 티켓_발권수수료_은행입금 { get; set; }
        public virtual DbSet<판매제휴그룹세부> 판매제휴그룹세부 { get; set; }
        public virtual DbSet<판매주문외부연동로그> 판매주문외부연동로그 { get; set; }
        public virtual DbSet<판매커미션정책> 판매커미션정책 { get; set; }
        public virtual DbSet<VIEW_거래처직원> VIEW_거래처직원 { get; set; }
        public virtual DbSet<VIEW_도시_공항> VIEW_도시_공항 { get; set; }
        public virtual DbSet<VIEW_사원포팅용> VIEW_사원포팅용 { get; set; }
        public virtual DbSet<VIEW_상품정보> VIEW_상품정보 { get; set; }
        public virtual DbSet<VIEW_상품조건코드> VIEW_상품조건코드 { get; set; }
        public virtual DbSet<V공동구매항공권> V공동구매항공권 { get; set; }
        public virtual DbSet<V단체> V단체 { get; set; }
        public virtual DbSet<V판매아이템> V판매아이템 { get; set; }
    }
}
