//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSync_FileList
    {
        public string FileCode { get; set; }
        public int FileNo { get; set; }
        public string AppCode { get; set; }
        public int Seq { get; set; }
        public bool isUse { get; set; }
        public string ServerRoot { get; set; }
        public string ServerPath { get; set; }
        public string ServerFileName { get; set; }
        public string LocalRoot { get; set; }
        public string LocalPath { get; set; }
        public string LocalFileName { get; set; }
        public bool isFinalExecute { get; set; }
        public string CopyMode { get; set; }
        public string File_Version { get; set; }
        public Nullable<long> File_Size { get; set; }
        public bool isExtract { get; set; }
        public string ExtractRoot { get; set; }
        public string ExtractPath { get; set; }
        public string isRegSvr { get; set; }
        public bool isExecute { get; set; }
        public string ExecuteArgs { get; set; }
        public bool isWait { get; set; }
        public System.DateTime RegDate { get; set; }
        public int RegUserId { get; set; }
    }
}
