//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_상품정보
    {
        public long 상품번호 { get; set; }
        public Nullable<long> 템플릿번호 { get; set; }
        public Nullable<bool> 표시여부 { get; set; }
        public string 항목구분 { get; set; }
        public string 항목명 { get; set; }
        public string 내용 { get; set; }
    }
}
