//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_도시_공항
    {
        public string 도시코드 { get; set; }
        public string 도시한글명 { get; set; }
        public string 도시영문명 { get; set; }
        public string 공항코드 { get; set; }
        public string 공항한글명 { get; set; }
        public string 공항영문명 { get; set; }
        public Nullable<double> 공항위도 { get; set; }
        public Nullable<double> 공항경도 { get; set; }
    }
}
