//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_상품조건코드
    {
        public string CID { get; set; }
        public string 코드종류 { get; set; }
        public string 코드종류명 { get; set; }
        public string 코드명 { get; set; }
    }
}
