//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V공동구매항공권
    {
        public long 단체번호 { get; set; }
        public Nullable<long> 재고번호 { get; set; }
        public long 상품번호 { get; set; }
        public string 상품종류 { get; set; }
        public System.DateTime 행사시작일시 { get; set; }
        public Nullable<System.DateTime> 행사종료일시 { get; set; }
    }
}
