//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 가격모델
    {
        public long 가격모델번호 { get; set; }
        public string 모델명 { get; set; }
        public string 판매채널구분 { get; set; }
        public string 제휴그룹 { get; set; }
        public Nullable<short> 최소잔여수량 { get; set; }
        public Nullable<short> 최대잔여수량 { get; set; }
        public decimal 판매마진율 { get; set; }
        public decimal 커미션율 { get; set; }
        public decimal 예상커미션율 { get; set; }
    }
}
