//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 개체
    {
        public long 개체번호 { get; set; }
        public string 개체구분 { get; set; }
        public string 개체명 { get; set; }
        public string 한글성명 { get; set; }
        public string 영문성명 { get; set; }
        public string 별칭 { get; set; }
        public string 대표연락처 { get; set; }
        public string 이메일 { get; set; }
        public string 전화 { get; set; }
        public string 주소 { get; set; }
    }
}
