//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 개체관계
    {
        public long 개체번호1 { get; set; }
        public long 개체번호2 { get; set; }
        public string 관계종류 { get; set; }
        public System.DateTime 관계일시작 { get; set; }
        public System.DateTime 관계일종료 { get; set; }
    }
}
