//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 거래처분류
    {
        public int 일련번호 { get; set; }
        public string 사업분류 { get; set; }
        public string 대분류 { get; set; }
        public string 중분류 { get; set; }
        public string 소분류 { get; set; }
        public string 소분류명 { get; set; }
        public bool 사용 { get; set; }
        public string 비고 { get; set; }
        public Nullable<System.DateTime> 저장일시 { get; set; }
        public Nullable<long> 저장자 { get; set; }
    }
}
