//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 거래처첨부파일
    {
        public long 거래처번호 { get; set; }
        public string 파일구분 { get; set; }
        public string 파일경로 { get; set; }
        public string OCR { get; set; }
    }
}
