//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 거래처
    {
        public long 거래처번호 { get; set; }
        public string 거래처구분 { get; set; }
        public string 판매처분류 { get; set; }
        public string 거래처명 { get; set; }
        public string 사업자번호 { get; set; }
        public string 업태명 { get; set; }
        public string 종목명 { get; set; }
        public string 대표자명 { get; set; }
        public string 사업자명 { get; set; }
        public string 사업장명 { get; set; }
        public string 청구담당자명 { get; set; }
        public string 청구담당이메일 { get; set; }
        public string 청구담당전화 { get; set; }
        public string 비고 { get; set; }
        public string 거래상태 { get; set; }
        public Nullable<bool> 판매가능여부 { get; set; }
        public Nullable<short> 미수유예일수 { get; set; }
        public Nullable<bool> 업체결제여부 { get; set; }
        public Nullable<bool> 출금가능여부 { get; set; }
        public Nullable<bool> 계산서발행여부 { get; set; }
    }
}
