//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 거래처직원
    {
        public long 거래처번호 { get; set; }
        public long 직원번호 { get; set; }
        public string 작업그룹 { get; set; }
        public string 부서명 { get; set; }
        public string 직위명 { get; set; }
        public string 직책명 { get; set; }
        public string 담당업무 { get; set; }
        public Nullable<bool> 사원여부 { get; set; }
        public Nullable<bool> 대표자여부 { get; set; }
        public Nullable<bool> 관리자여부 { get; set; }
        public Nullable<bool> 퇴사여부 { get; set; }
        public string 전화 { get; set; }
        public string 팩스 { get; set; }
        public string 이메일 { get; set; }
        public string 주소 { get; set; }
    }
}
