//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 거래처담당
    {
        public long 거래처번호 { get; set; }
        public long 직원번호 { get; set; }
        public Nullable<long> 미수담당 { get; set; }
        public Nullable<long> 영업담당 { get; set; }
        public Nullable<long> 예약운영 { get; set; }
        public Nullable<long> 발권담당 { get; set; }
    }
}
