//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 공유
    {
        public long 공유번호 { get; set; }
        public Nullable<System.DateTime> 공유일시 { get; set; }
        public long 공유자번호 { get; set; }
        public string 연락처 { get; set; }
        public string 참조구분 { get; set; }
        public Nullable<long> 참조번호 { get; set; }
    }
}
