//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 공항
    {
        public string 공항코드 { get; set; }
        public string 국가코드 { get; set; }
        public string 도시코드 { get; set; }
        public string 공항명 { get; set; }
        public string 한글명 { get; set; }
        public string 영문명 { get; set; }
        public Nullable<double> 위도 { get; set; }
        public Nullable<double> 경도 { get; set; }
        public string 홈페이지 { get; set; }
        public Nullable<short> 타임존 { get; set; }
    }
}
