//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 구매주문
    {
        public long 구매번호 { get; set; }
        public long 단체번호 { get; set; }
        public Nullable<System.DateTime> 출발일 { get; set; }
        public string 품목코드 { get; set; }
        public string 보험료코드 { get; set; }
        public string 원가구분 { get; set; }
        public string 참조구분 { get; set; }
        public Nullable<long> 참조번호 { get; set; }
        public string 작성자구분 { get; set; }
        public Nullable<long> 작성자번호 { get; set; }
        public Nullable<bool> 랜드사등록여부 { get; set; }
        public string 인보이스파일경로 { get; set; }
        public Nullable<long> 공급업체번호 { get; set; }
        public long 구매총액 { get; set; }
        public string 통화코드 { get; set; }
        public string 통화 { get; set; }
        public long 구매금액 { get; set; }
        public long 구매단가 { get; set; }
        public long 유류제세금 { get; set; }
        public Nullable<short> 구매수량 { get; set; }
        public decimal 구매환율 { get; set; }
        public Nullable<bool> 고정환율여부 { get; set; }
        public Nullable<bool> 선급여부 { get; set; }
        public Nullable<long> 선급번호 { get; set; }
        public Nullable<bool> 손실분여부 { get; set; }
        public long 출금총액 { get; set; }
        public long 출금가액 { get; set; }
        public long 공급가액 { get; set; }
        public long 부가세액 { get; set; }
        public Nullable<bool> 미불여부 { get; set; }
        public Nullable<long> 미불분개번호 { get; set; }
        public Nullable<bool> 출금여부 { get; set; }
        public string 출금방식 { get; set; }
        public string 외환구분 { get; set; }
        public string 외환송금번호 { get; set; }
        public Nullable<long> 출금분개번호 { get; set; }
        public Nullable<bool> 계산서발행여부 { get; set; }
        public Nullable<long> 공급가액분개번호 { get; set; }
        public Nullable<long> 부가세액분개번호 { get; set; }
        public string 비고 { get; set; }
    }
}
