//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 국가
    {
        public string 국가코드 { get; set; }
        public string 국가명 { get; set; }
        public string 한글이름 { get; set; }
        public string 영문이름 { get; set; }
        public string 대륙코드 { get; set; }
        public string 대륙영문이름 { get; set; }
        public string 수도영문이름 { get; set; }
        public string 국가전화코드 { get; set; }
        public string 대표통화코드 { get; set; }
        public string 통화코드내역 { get; set; }
        public string 대표언어코드 { get; set; }
        public string 언어코드내역 { get; set; }
        public Nullable<bool> 비자 { get; set; }
    }
}
