//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 국가_출입국안내
    {
        public string 국가코드 { get; set; }
        public string 서류종류 { get; set; }
        public string 서류명 { get; set; }
        public string 파일경로 { get; set; }
        public Nullable<bool> 노출여부 { get; set; }
    }
}
