//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 국내도로명주소
    {
        public long 번호 { get; set; }
        public string 우편번호 { get; set; }
        public string 시도 { get; set; }
        public string 시군구 { get; set; }
        public string 법정동명 { get; set; }
        public string 도로명 { get; set; }
        public string 읍면동_기존 { get; set; }
        public string 기타_기존 { get; set; }
    }
}
