//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 국내지번주소
    {
        public long 번호 { get; set; }
        public string 우편번호 { get; set; }
        public string 시도 { get; set; }
        public string 시군구 { get; set; }
        public string 읍면동 { get; set; }
        public string 리 { get; set; }
        public string 도서 { get; set; }
        public string 번지 { get; set; }
        public string 건물명 { get; set; }
    }
}
