//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 기초코드
    {
        public string CID { get; set; }
        public string 코드종류 { get; set; }
        public string 코드종류명 { get; set; }
        public string 코드값 { get; set; }
        public string 코드명 { get; set; }
        public Nullable<bool> 사용 { get; set; }
        public Nullable<short> 정렬 { get; set; }
        public string 코드설명 { get; set; }
        public string 참조테이블 { get; set; }
        public string 참조컬럼 { get; set; }
        public string 상태01 { get; set; }
        public string 상태02 { get; set; }
        public string 상태03 { get; set; }
        public string 상태04 { get; set; }
        public string 상태05 { get; set; }
        public string 상태06 { get; set; }
        public string 상태07 { get; set; }
        public string 상태08 { get; set; }
        public string 상태09 { get; set; }
        public string 상태10 { get; set; }
        public string 상태11 { get; set; }
        public string 상태12 { get; set; }
        public string 상태13 { get; set; }
        public string 상태14 { get; set; }
        public string 상태15 { get; set; }
        public string 상태16 { get; set; }
        public string 상태17 { get; set; }
        public string 상태18 { get; set; }
        public string 상태19 { get; set; }
        public string 상태20 { get; set; }
        public string 상태21 { get; set; }
        public string 상태22 { get; set; }
        public string 상태23 { get; set; }
        public string 상태24 { get; set; }
        public string 상태25 { get; set; }
        public string 상태26 { get; set; }
        public string 상태27 { get; set; }
        public string 상태28 { get; set; }
        public string 상태29 { get; set; }
        public string 상태30 { get; set; }
        public string 상태31 { get; set; }
        public string 상태32 { get; set; }
        public string 상태33 { get; set; }
        public Nullable<System.DateTime> 저장일시 { get; set; }
        public Nullable<long> 저장자 { get; set; }
        public Nullable<int> 테스트컬럼 { get; set; }
    }
}
