//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 닷컴구역
    {
        public long 구역번호 { get; set; }
        public string 구역구분 { get; set; }
        public string 구역명 { get; set; }
        public Nullable<short> 순서 { get; set; }
        public Nullable<long> 카달로그번호 { get; set; }
        public string 구분 { get; set; }
        public string 이미지경로 { get; set; }
        public string 랜딩경로 { get; set; }
        public Nullable<bool> 새창여부 { get; set; }
        public Nullable<long> 참조번호 { get; set; }
    }
}
