//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 댓글
    {
        public long 댓글번호 { get; set; }
        public long 리뷰번호 { get; set; }
        public long 작성자번호 { get; set; }
        public Nullable<System.DateTime> 작성일 { get; set; }
        public string 댓글1 { get; set; }
    }
}
