//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 도시
    {
        public string 도시코드 { get; set; }
        public string 국가코드 { get; set; }
        public short 순서 { get; set; }
        public string 도시명 { get; set; }
        public string 한글이름 { get; set; }
        public string 영문이름 { get; set; }
        public Nullable<long> 장소번호 { get; set; }
        public string 구글키 { get; set; }
        public Nullable<long> 일정등록수 { get; set; }
    }
}
