//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 리뷰
    {
        public long 리뷰번호 { get; set; }
        public long 작성자번호 { get; set; }
        public string 참조구분 { get; set; }
        public Nullable<long> 참조번호 { get; set; }
        public string 제목 { get; set; }
        public string 내용 { get; set; }
        public Nullable<System.DateTime> 작성일 { get; set; }
        public long 조회수 { get; set; }
        public Nullable<short> 평점 { get; set; }
    }
}
