//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 마일리지합산대상자
    {
        public long 신청번호 { get; set; }
        public string 대상자 { get; set; }
        public string 관계종류 { get; set; }
        public Nullable<bool> 동의여부 { get; set; }
        public Nullable<System.DateTime> 합산동의일 { get; set; }
        public Nullable<short> 마일리지차감순서 { get; set; }
    }
}
