//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 마일리지합산신청
    {
        public long 신청번호 { get; set; }
        public string 신청자 { get; set; }
        public Nullable<System.DateTime> 신청일 { get; set; }
        public Nullable<bool> 전체동의여부 { get; set; }
    }
}
