//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 마일리지합산해지
    {
        public long 신청번호 { get; set; }
        public string 대상자 { get; set; }
        public Nullable<System.DateTime> 해지일 { get; set; }
        public string 해지사유 { get; set; }
    }
}
