//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 메세지템플릿
    {
        public string 작성자연락처 { get; set; }
        public string 제목 { get; set; }
        public string 색상 { get; set; }
        public bool 간단주문요약표시여부 { get; set; }
        public bool 회사로고표시여부 { get; set; }
        public string 헤더타입 { get; set; }
        public string 헤더 { get; set; }
        public bool 주문요약표시여부 { get; set; }
        public bool 안내문구표시여부 { get; set; }
        public string 안내문구 { get; set; }
        public bool 감사문구표시여부 { get; set; }
        public string 감사문구 { get; set; }
        public bool 예약자표시여부 { get; set; }
        public bool 고객요청사항표시여부 { get; set; }
        public bool 결제내역표시여부 { get; set; }
        public string 푸터형식 { get; set; }
        public string 푸터 { get; set; }
        public bool 주문내역표시여부 { get; set; }
        public bool QR코드표시여부 { get; set; }
        public bool 미팅표시여부 { get; set; }
        public bool 지도표시여부 { get; set; }
        public bool 주문상세표시여부 { get; set; }
        public bool 여행자표시여부 { get; set; }
        public bool 상품추가메시지표시여부 { get; set; }
        public bool 특별규정표시여부 { get; set; }
        public bool 일반규정표시여부 { get; set; }
        public bool 소셜주소표시여부 { get; set; }
        public bool 첨부파일여부 { get; set; }
    }
}
