//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 메세지이력
    {
        public long 발송번호 { get; set; }
        public Nullable<long> 발신자 { get; set; }
        public string 발신자주소 { get; set; }
        public Nullable<long> 수신자 { get; set; }
        public string 수신자주소 { get; set; }
        public string 참조구분 { get; set; }
        public Nullable<long> 참조번호 { get; set; }
        public Nullable<System.DateTime> 등록일시 { get; set; }
        public Nullable<System.DateTime> 발송일시 { get; set; }
        public Nullable<bool> 발송수단 { get; set; }
        public string 제목 { get; set; }
        public string 스크립트 { get; set; }
        public string 내용 { get; set; }
        public Nullable<bool> 수신확인여부 { get; set; }
    }
}
