//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 부가서비스
    {
        public long 부가서비스번호 { get; set; }
        public string 서비스구분 { get; set; }
        public string 국가코드 { get; set; }
        public string 도시코드 { get; set; }
        public Nullable<long> 장소코드 { get; set; }
        public string 서비스명 { get; set; }
        public long 서비스가격 { get; set; }
        public string 통화코드 { get; set; }
        public long 단가 { get; set; }
        public decimal 마크업 { get; set; }
        public string 설명 { get; set; }
        public string 이미지경로 { get; set; }
    }
}
