//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 부서
    {
        public long 부서번호 { get; set; }
        public Nullable<long> 상위번호 { get; set; }
        public string 부서명 { get; set; }
        public string 부서구분 { get; set; }
        public string 부서유형 { get; set; }
        public string 부서역할 { get; set; }
        public Nullable<bool> 수익부서여부 { get; set; }
        public Nullable<long> 책임자 { get; set; }
        public string 책임자직책 { get; set; }
        public Nullable<bool> 사용여부 { get; set; }
        public Nullable<System.DateTime> 사용일시작 { get; set; }
        public Nullable<System.DateTime> 사용일종료 { get; set; }
        public Nullable<bool> 모두톡_내부 { get; set; }
        public Nullable<bool> 모두톡_여행사 { get; set; }
        public Nullable<bool> 모두톡_랜드사 { get; set; }
        public Nullable<long> 거래처번호 { get; set; }
        public Nullable<long> 직원번호 { get; set; }
    }
}
