//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 브랜드
    {
        public string 브랜드명 { get; set; }
        public string 조건코드 { get; set; }
        public decimal 상품커미션율 { get; set; }
        public decimal 공헌이익율 { get; set; }
        public string 비고 { get; set; }
    }
}
