//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 브랜드가격정책
    {
        public string 브랜드명 { get; set; }
        public long 카데고리번호 { get; set; }
        public Nullable<short> 몇일전시작 { get; set; }
        public Nullable<short> 몇일전마지막 { get; set; }
        public Nullable<short> 잔여수량시작 { get; set; }
        public Nullable<short> 잔여수량마지막 { get; set; }
        public Nullable<short> 주문수량시작 { get; set; }
        public Nullable<short> 주문수량마지막 { get; set; }
        public decimal 공헌이익율 { get; set; }
    }
}
