//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 비자
    {
        public string 국가코드 { get; set; }
        public Nullable<long> 담당부서 { get; set; }
        public Nullable<long> 담당사원 { get; set; }
        public string 비자설명 { get; set; }
        public Nullable<short> 몇일전접수마감 { get; set; }
    }
}
