//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 빌링_티켓
    {
        public string 티켓번호 { get; set; }
        public string 항공코드번호 { get; set; }
        public string TERM { get; set; }
        public string 발권지점번호 { get; set; }
        public string 발권지점코드 { get; set; }
        public long SHOWN { get; set; }
        public long DISC { get; set; }
        public long COMM { get; set; }
        public long TAX { get; set; }
        public long CASH { get; set; }
        public long CARD { get; set; }
        public string 비고 { get; set; }
        public string NVR { get; set; }
    }
}
