//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 빌링_계산서
    {
        public long 빌링_계산서번호 { get; set; }
        public Nullable<System.DateTime> 부가세발행일 { get; set; }
        public long 공급가액 { get; set; }
        public long 부가세액 { get; set; }
        public string 사업자번호_공급자 { get; set; }
        public Nullable<long> 지점 { get; set; }
        public string 사업자번호_공급받는자 { get; set; }
        public Nullable<long> 거래처번호 { get; set; }
        public Nullable<long> 분개번호 { get; set; }
    }
}
