//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 사용자_환경설정
    {
        public int 일련번호 { get; set; }
        public int 사용자번호 { get; set; }
        public string 프로젝트코드 { get; set; }
        public string 설정항목코드 { get; set; }
        public string 설정값 { get; set; }
        public System.DateTime 저장일시 { get; set; }
    }
}
