//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 사원
    {
        public long 개체번호 { get; set; }
        public string 사원명 { get; set; }
        public string 내선 { get; set; }
        public string 사번 { get; set; }
        public string 캡스번호 { get; set; }
        public Nullable<bool> 퇴직여부 { get; set; }
        public Nullable<long> 대표계좌번호 { get; set; }
        public Nullable<long> 소속본부번호 { get; set; }
        public Nullable<long> 소속부문번호 { get; set; }
        public long 소속부서번호 { get; set; }
        public Nullable<long> 소속팀번호 { get; set; }
        public Nullable<long> 근무본부번호 { get; set; }
        public Nullable<long> 근무부문번호 { get; set; }
        public long 근무부서번호 { get; set; }
        public Nullable<long> 근무팀번호 { get; set; }
        public string 근무지대분류 { get; set; }
        public string 근무지중분류 { get; set; }
        public string 근무지 { get; set; }
        public string 작업그룹 { get; set; }
        public string 직위 { get; set; }
        public string 호칭 { get; set; }
        public string 운영직책 { get; set; }
        public string 공식직책 { get; set; }
        public string 직무대분류 { get; set; }
        public string 직무중분류 { get; set; }
        public string 직무 { get; set; }
        public Nullable<long> 상위결재자 { get; set; }
        public Nullable<bool> 대결여부 { get; set; }
        public Nullable<long> 기본대결자 { get; set; }
        public Nullable<long> 상위평가자 { get; set; }
        public string 고용형태 { get; set; }
        public string 고용형태상세 { get; set; }
        public string 고과그룹 { get; set; }
        public string 임금체계 { get; set; }
        public string 직급 { get; set; }
        public string 임금정책선 { get; set; }
        public string 임금수준 { get; set; }
        public Nullable<int> SORT { get; set; }
        public Nullable<System.DateTime> 입사일 { get; set; }
        public Nullable<System.DateTime> 경력기준일 { get; set; }
        public Nullable<System.DateTime> 퇴직예정일 { get; set; }
        public Nullable<System.DateTime> 퇴직일 { get; set; }
        public string 소속구분 { get; set; }
        public string 담당업무 { get; set; }
        public string 당일휴가정보 { get; set; }
        public string 휴가정보 { get; set; }
        public string 법인카드번호 { get; set; }
        public Nullable<bool> 활성여부_AD { get; set; }
        public Nullable<bool> 활성여부_O365 { get; set; }
        public Nullable<bool> 테스트계정여부 { get; set; }
        public Nullable<bool> 삼자카드결제가능여부 { get; set; }
        public string 근로계약기한 { get; set; }
        public string 노동조합 { get; set; }
        public string 노사협의회 { get; set; }
        public string 더존번호 { get; set; }
        public Nullable<bool> 임원여부 { get; set; }
    }
}
