//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 상품시즌상세
    {
        public long 정책번호 { get; set; }
        public System.DateTime 시작일 { get; set; }
        public System.DateTime 종료일 { get; set; }
        public string 요일_YYYYYYY_ { get; set; }
    }
}
