//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 상품시즌정책
    {
        public long 정책번호 { get; set; }
        public string 년도 { get; set; }
        public string 시즌 { get; set; }
        public long 지역번호 { get; set; }
        public decimal 기준마크업율 { get; set; }
        public decimal 기준커미션율 { get; set; }
    }
}
