//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 상품재고상세
    {
        public long 재고상세번호 { get; set; }
        public long 재고번호 { get; set; }
        public long 성인원가 { get; set; }
        public string 공급방식_J3_ { get; set; }
        public Nullable<short> 보유수량 { get; set; }
        public Nullable<short> 반납수량 { get; set; }
        public string 확정상태_J8_ { get; set; }
        public Nullable<bool> 판매마감여부 { get; set; }
        public Nullable<System.DateTime> 판매마감일 { get; set; }
        public Nullable<System.DateTime> 발권예정일 { get; set; }
    }
}
