//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 상품지역
    {
        public long 지역번호 { get; set; }
        public string 분류1 { get; set; }
        public string 분류2 { get; set; }
        public string 지역명1 { get; set; }
        public string 지역명2 { get; set; }
    }
}
