//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 상품카테고리
    {
        public long 카테고리번호 { get; set; }
        public string 카테고리명 { get; set; }
        public string 방문도시 { get; set; }
        public string 방문도시명 { get; set; }
        public string 방문국가 { get; set; }
        public string 방문국가명 { get; set; }
    }
}
