//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 상품조건
    {
        public string 조건코드 { get; set; }
        public string 최소출발인원 { get; set; }
        public string 현지팁 { get; set; }
        public string 옵션 { get; set; }
        public string 쇼핑 { get; set; }
        public string 공항세 { get; set; }
        public string 입장료 { get; set; }
        public string 가이드 { get; set; }
        public string 보험보장액 { get; set; }
        public string 동반최소인원 { get; set; }
        public string 자유일정 { get; set; }
        public string 현지송영 { get; set; }
        public string 비자 { get; set; }
        public string 현지경비 { get; set; }
    }
}
