//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 상품비고마스터
    {
        public long 비고번호 { get; set; }
        public string 구분 { get; set; }
        public string 항목명 { get; set; }
        public string 내용 { get; set; }
    }
}
