//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 상품메세지
    {
        public long 상품번호 { get; set; }
        public string 메세지용도 { get; set; }
        public string 전송방식 { get; set; }
        public bool 안내문구표시여부 { get; set; }
        public string 안내문구 { get; set; }
        public bool 감사문구표시여부 { get; set; }
        public string 감사문구 { get; set; }
        public bool 파일첨부여부 { get; set; }
        public bool 전송여부 { get; set; }
        public string 전송시간타입 { get; set; }
        public short 전송시간값 { get; set; }
        public string 전송시간기준 { get; set; }
        public decimal 완납비율 { get; set; }
    }
}
