//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 상품담당
    {
        public long 상품담당번호 { get; set; }
        public long 상품번호 { get; set; }
        public string 담당역할 { get; set; }
        public Nullable<long> 담당부서 { get; set; }
        public Nullable<long> 담당사원 { get; set; }
        public Nullable<System.DateTime> 담당일시작 { get; set; }
        public Nullable<System.DateTime> 담당일종료 { get; set; }
    }
}
