//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 상품재고여정
    {
        public long 재고번호 { get; set; }
        public short 일차 { get; set; }
        public Nullable<System.DateTime> 출발일시 { get; set; }
        public Nullable<System.DateTime> 도착일시 { get; set; }
        public short 순서 { get; set; }
        public string 시간 { get; set; }
        public string 출발시간 { get; set; }
        public string 도착시간 { get; set; }
        public string 출도착 { get; set; }
        public string 출발지 { get; set; }
        public string 도착지 { get; set; }
        public string 편명 { get; set; }
        public string 비행시간 { get; set; }
    }
}
