//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 상품
    {
        public long 상품번호 { get; set; }
        public long 지역번호 { get; set; }
        public Nullable<long> 카테고리번호 { get; set; }
        public Nullable<long> 카달로그번호 { get; set; }
        public string 상품종류 { get; set; }
        public string 상품명 { get; set; }
        public Nullable<short> 박수 { get; set; }
        public Nullable<short> 일수 { get; set; }
        public Nullable<bool> 상품여정유무 { get; set; }
        public string 출도착 { get; set; }
        public string 상품여정 { get; set; }
        public Nullable<bool> 관광유무 { get; set; }
        public string 관광도시 { get; set; }
        public string 관광도시명 { get; set; }
        public string 관광장소 { get; set; }
        public string 관광장소명 { get; set; }
        public Nullable<bool> 숙박유무 { get; set; }
        public Nullable<bool> 숙박재고여부 { get; set; }
        public string 숙박도시 { get; set; }
        public string 숙박도시명 { get; set; }
        public string 숙박장소 { get; set; }
        public string 숙박장소명 { get; set; }
        public Nullable<bool> 상품일정유무 { get; set; }
        public string 상품일정 { get; set; }
        public string 간략설명 { get; set; }
        public string 상세설명 { get; set; }
        public string 태그리스트 { get; set; }
        public string 대표이미지경로 { get; set; }
        public string 좌석확정기준 { get; set; }
        public string 확정처리방식 { get; set; }
        public Nullable<bool> 대기예약허용 { get; set; }
        public string 완납시한기준 { get; set; }
        public Nullable<short> 완납시한 { get; set; }
        public string 신청금비율구분 { get; set; }
        public decimal 신청금비율 { get; set; }
        public Nullable<long> 담당부서 { get; set; }
        public Nullable<long> 담당자 { get; set; }
        public Nullable<long> 참조번호 { get; set; }
    }
}
