//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 상품취소료규정
    {
        public long 상품번호 { get; set; }
        public short 몇일전시작 { get; set; }
        public short 몇일전마지막 { get; set; }
        public decimal 취소료비율 { get; set; }
    }
}
