//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 상품지역브랜드
    {
        public long 브랜드매핑번호 { get; set; }
        public string 브랜드코드 { get; set; }
        public long 지역번호 { get; set; }
        public string 조건코드 { get; set; }
        public Nullable<System.DateTime> 등록일 { get; set; }
        public Nullable<long> 등록자 { get; set; }
    }
}
