//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 상품옵션
    {
        public long 상품옵션번호 { get; set; }
        public long 상품번호 { get; set; }
        public string 옵션명 { get; set; }
        public string 조건1 { get; set; }
        public string 조건2 { get; set; }
        public string 조건3 { get; set; }
        public string 조건4 { get; set; }
    }
}
