//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 상품부가서비스
    {
        public long 상품번호 { get; set; }
        public string 서비스번호 { get; set; }
        public long 서비스요금 { get; set; }
        public long 원가 { get; set; }
        public string 비고_JSON_ { get; set; }
    }
}
