//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 상품단체
    {
        public long 단체번호 { get; set; }
        public Nullable<long> 상품번호 { get; set; }
        public string 조건코드 { get; set; }
        public Nullable<long> 모델번호 { get; set; }
        public Nullable<long> 입찰번호 { get; set; }
        public Nullable<long> 재고번호 { get; set; }
        public Nullable<System.DateTime> 출발일 { get; set; }
        public System.DateTime 행사시작일시 { get; set; }
        public Nullable<System.DateTime> 행사종료일시 { get; set; }
        public Nullable<short> 배정수량 { get; set; }
        public Nullable<short> 판매수량 { get; set; }
        public Nullable<short> 판매객실수량 { get; set; }
        public Nullable<bool> 소아판매여부 { get; set; }
        public Nullable<bool> 유아판매여부 { get; set; }
        public long 원가총액 { get; set; }
        public long 재고원가 { get; set; }
        public long 지상원가 { get; set; }
        public long 기타원가 { get; set; }
        public Nullable<bool> 취소여부 { get; set; }
        public Nullable<long> 운영부서 { get; set; }
        public Nullable<long> 수익부서 { get; set; }
        public string 센딩구분 { get; set; }
        public string 미팅장소 { get; set; }
        public Nullable<System.TimeSpan> 미팅시간 { get; set; }
        public Nullable<long> SM { get; set; }
        public Nullable<long> MD { get; set; }
        public Nullable<long> OP { get; set; }
        public Nullable<long> 항공 { get; set; }
        public Nullable<long> 발권 { get; set; }
        public Nullable<long> 숙박 { get; set; }
        public Nullable<long> 인솔자 { get; set; }
    }
}
