//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 상품원가표
    {
        public long 원가번호 { get; set; }
        public long 상품번호 { get; set; }
        public long 가격번호 { get; set; }
        public Nullable<long> 공급업체번호 { get; set; }
        public string 원가항목코드 { get; set; }
        public Nullable<bool> 공용원가여부 { get; set; }
        public string 참조구분 { get; set; }
        public Nullable<long> 참조번호 { get; set; }
        public string 연령구분 { get; set; }
        public string 통화코드 { get; set; }
        public decimal 환율 { get; set; }
        public long 공급단가 { get; set; }
    }
}
