//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 상품가격
    {
        public long 가격번호 { get; set; }
        public long 단체번호 { get; set; }
        public Nullable<short> 순서 { get; set; }
        public string 단체명 { get; set; }
        public string 판매채널구분 { get; set; }
        public string 제휴그룹 { get; set; }
        public decimal 기준마크업율 { get; set; }
        public decimal 기준커미션율 { get; set; }
        public long 성인가격 { get; set; }
        public long 소아가격 { get; set; }
        public long 유아가격 { get; set; }
        public Nullable<bool> 판매여부 { get; set; }
        public Nullable<System.DateTime> 판매일시작 { get; set; }
        public Nullable<System.DateTime> 판매일종료 { get; set; }
        public Nullable<long> 제휴그룹번호 { get; set; }
    }
}
