//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 상품제휴가격
    {
        public long 제휴가격번호 { get; set; }
        public long 단체번호 { get; set; }
        public string 제휴그룹명 { get; set; }
        public string 제휴그룹코드 { get; set; }
        public Nullable<bool> CRS { get; set; }
        public Nullable<bool> BP { get; set; }
        public Nullable<bool> 마트 { get; set; }
        public string 제휴단체명 { get; set; }
        public long 제휴가격_성인 { get; set; }
        public long 제휴가격_소아 { get; set; }
        public long 제휴가격_유아 { get; set; }
        public decimal 커미션율 { get; set; }
        public decimal 마크업율 { get; set; }
        public decimal 영업수익율 { get; set; }
        public decimal 상품수익율 { get; set; }
        public decimal 결제수수료율 { get; set; }
        public Nullable<bool> 판매마감여부 { get; set; }
        public Nullable<long> 참조번호 { get; set; }
        public long 원가총액 { get; set; }
        public long 항공원가 { get; set; }
        public long 지상원가 { get; set; }
        public long 기타원가 { get; set; }
        public Nullable<bool> 제휴여부 { get; set; }
    }
}
