//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 선급보증금
    {
        public long 선급번호 { get; set; }
        public Nullable<System.DateTime> 행사일시작 { get; set; }
        public Nullable<System.DateTime> 행사일마지막 { get; set; }
        public Nullable<long> 공급업체번호 { get; set; }
        public string 선급구분 { get; set; }
        public long 선급보증총액 { get; set; }
        public long 선급대체총액 { get; set; }
    }
}
