//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 세금계산서
    {
        public long 계산서번호 { get; set; }
        public Nullable<System.DateTime> 발행일 { get; set; }
        public Nullable<long> 공급자 { get; set; }
        public Nullable<long> 공급받는자 { get; set; }
        public long 공급가액 { get; set; }
        public long 부가세액 { get; set; }
        public long 부가세잔액 { get; set; }
        public long 공급가잔액 { get; set; }
    }
}
