//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 센딩
    {
        public long 센딩번호 { get; set; }
        public long 단체번호 { get; set; }
        public Nullable<System.DateTime> 출발일 { get; set; }
        public string 센딩장소 { get; set; }
        public string 전달사항 { get; set; }
        public Nullable<bool> 요청 { get; set; }
        public long 등록자 { get; set; }
        public Nullable<System.DateTime> 등록일시 { get; set; }
        public Nullable<System.DateTime> 삭제일시 { get; set; }
        public Nullable<long> 삭제자 { get; set; }
        public Nullable<long> 확인자 { get; set; }
        public Nullable<System.DateTime> 확인일시 { get; set; }
    }
}
