//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 숙박재고
    {
        public long 숙박재고번호 { get; set; }
        public long 장소번호 { get; set; }
        public System.DateTime 날짜 { get; set; }
        public Nullable<long> 견적번호 { get; set; }
        public Nullable<long> 공급업체번호 { get; set; }
        public string 보유상태 { get; set; }
        public Nullable<short> 총보유수량 { get; set; }
        public Nullable<short> 총판매수량 { get; set; }
        public string 장소코드 { get; set; }
    }
}
