//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 아이템담당배정
    {
        public string 품목코드 { get; set; }
        public string 품목그룹 { get; set; }
        public long 거래처번호 { get; set; }
        public long 거래처직원번호 { get; set; }
        public long 발권담당자번호 { get; set; }
        public Nullable<bool> 사용여부 { get; set; }
        public Nullable<bool> 배정여부 { get; set; }
        public Nullable<bool> 공휴일제외여부 { get; set; }
        public string 배정가능요일 { get; set; }
        public Nullable<int> 슬롯수 { get; set; }
        public Nullable<int> 배정슬롯수 { get; set; }
        public Nullable<System.DateTime> 마지막배정일시 { get; set; }
        public Nullable<long> 수정자 { get; set; }
        public Nullable<System.DateTime> 수정일시 { get; set; }
    }
}
