//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 알림
    {
        public string 알림코드 { get; set; }
        public int 알림번호 { get; set; }
        public System.DateTime 등록일 { get; set; }
        public System.DateTime 알림예약일 { get; set; }
        public Nullable<System.DateTime> 알림발송일 { get; set; }
        public int 발신자번호 { get; set; }
        public string 발신자명 { get; set; }
        public int 수신자번호 { get; set; }
        public string 수신자명 { get; set; }
        public string 프로젝트코드 { get; set; }
        public string 알림유형코드 { get; set; }
        public string 중요도코드 { get; set; }
        public string 메시지 { get; set; }
        public bool 읽음여부 { get; set; }
        public Nullable<System.DateTime> 읽은일 { get; set; }
    }
}
