//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 연락처
    {
        public long 연락처번호 { get; set; }
        public long 개체번호 { get; set; }
        public string 연락처종류 { get; set; }
        public string 연락처구분 { get; set; }
        public Nullable<bool> 대표연락처 { get; set; }
        public string 연락처1 { get; set; }
        public string 우편번호 { get; set; }
    }
}
