//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 웹기획전
    {
        public long 기획전번호 { get; set; }
        public string 항목구분 { get; set; }
        public string 타입명내역 { get; set; }
        public string 기획전명 { get; set; }
        public string 간략타이틀 { get; set; }
        public string 설명 { get; set; }
        public string 키워드 { get; set; }
        public string 경로 { get; set; }
        public Nullable<long> 작업자 { get; set; }
        public Nullable<long> 요청자 { get; set; }
        public Nullable<System.DateTime> 요청일 { get; set; }
        public Nullable<bool> 게시 { get; set; }
        public Nullable<System.DateTime> 게시시작일 { get; set; }
        public Nullable<System.DateTime> 게시만료일 { get; set; }
        public Nullable<short> 노출날짜수 { get; set; }
        public Nullable<bool> 제휴여부 { get; set; }
        public Nullable<bool> 모바일사용여부 { get; set; }
        public Nullable<short> 모바일순서 { get; set; }
        public Nullable<bool> 일정표표시여부 { get; set; }
        public Nullable<bool> 이미지_풀사이즈여부 { get; set; }
        public string 이미지1 { get; set; }
        public string 이미지2 { get; set; }
        public string 이미지3 { get; set; }
        public string 이미지4 { get; set; }
        public string 이미지5 { get; set; }
        public string 이미지6 { get; set; }
        public string 이미지7 { get; set; }
        public string 이미지8 { get; set; }
        public string 이미지9 { get; set; }
        public string 이미지F { get; set; }
        public string 이미지10 { get; set; }
        public string 이미지11 { get; set; }
        public string 이미지_모바일 { get; set; }
        public string 이미지_자유여행 { get; set; }
        public string 이미지_국가대륙 { get; set; }
        public string 이미지_1100 { get; set; }
        public string GNB우측배너 { get; set; }
        public string 서브하단롤링배너 { get; set; }
        public string 서브하단고정배너 { get; set; }
        public string 키오스크이미지경로 { get; set; }
        public string 메인_섬네일 { get; set; }
        public string 제휴BP모바일메인배너 { get; set; }
        public string 제휴BP모바일하단배너 { get; set; }
        public string 닷컴태그 { get; set; }
        public string 모바일태그 { get; set; }
        public string 제휴모바일태그 { get; set; }
        public string 웹_탭구분 { get; set; }
        public string 모바일_탭구분 { get; set; }
        public string 웹_상품템플릿 { get; set; }
    }
}
