//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 웹구역
    {
        public long 웹구역번호 { get; set; }
        public string 웹구역종류 { get; set; }
        public long 웹사이트번호 { get; set; }
        public long 웹페이지번호 { get; set; }
        public Nullable<long> 카달로그번호 { get; set; }
        public string 웹구역명 { get; set; }
        public string 웹구역위치 { get; set; }
        public string 웹구역설명 { get; set; }
        public string 웹구역태그 { get; set; }
    }
}
