//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 웹이벤트구역
    {
        public long 구역번호 { get; set; }
        public Nullable<long> 기획전번호 { get; set; }
        public string 구역명 { get; set; }
        public string 구역위치 { get; set; }
        public string 구역설명 { get; set; }
        public string 구역태그 { get; set; }
        public string 이미지경로 { get; set; }
    }
}
