//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 웹사이트
    {
        public long 웹사이트번호 { get; set; }
        public string 웹사이트주소 { get; set; }
        public Nullable<long> 웹페이지번호 { get; set; }
        public string 웹사이트명 { get; set; }
        public Nullable<long> 거래처번호 { get; set; }
        public string 전시방식 { get; set; }
        public string 파일타입 { get; set; }
        public string 웹사이트종류 { get; set; }
        public string 로드방식 { get; set; }
        public string 시작경로 { get; set; }
        public string 도메인업체 { get; set; }
        public string 비고 { get; set; }
        public string 업체정보1 { get; set; }
        public string 업체정보2 { get; set; }
        public Nullable<long> 담당자 { get; set; }
        public Nullable<bool> 사용여부 { get; set; }
        public Nullable<System.DateTime> 등록일 { get; set; }
    }
}
