//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 웹페이지
    {
        public long 웹페이지번호 { get; set; }
        public Nullable<long> 상위번호 { get; set; }
        public Nullable<long> 웹사이트번호 { get; set; }
        public string 구분 { get; set; }
        public Nullable<short> 단계 { get; set; }
        public string 호스트 { get; set; }
        public string 파일경로 { get; set; }
        public string 페이지명 { get; set; }
        public string 매개변수 { get; set; }
        public Nullable<bool> 제휴 { get; set; }
        public Nullable<short> 노출순서 { get; set; }
        public Nullable<long> 관련경로번호 { get; set; }
        public Nullable<short> 노드레벨 { get; set; }
    }
}
