//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 유료센딩
    {
        public long 유료센딩번호 { get; set; }
        public long 주문번호 { get; set; }
        public Nullable<short> 주문수량 { get; set; }
        public System.TimeSpan 미팅시간 { get; set; }
        public string 미팅장소 { get; set; }
        public string 출발편명 { get; set; }
        public System.TimeSpan 출발시간 { get; set; }
        public Nullable<long> 센딩담당 { get; set; }
        public string 전달사항 { get; set; }
        public Nullable<bool> 고객통화여부 { get; set; }
        public long 유료센딩비용 { get; set; }
        public string 관계종류 { get; set; }
    }
}
