//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 은행계좌
    {
        public long 계좌일련번호 { get; set; }
        public long 계좌소유주 { get; set; }
        public string 계좌소유주명 { get; set; }
        public Nullable<bool> 대표계좌여부 { get; set; }
        public string 계좌번호 { get; set; }
        public string 은행명 { get; set; }
        public Nullable<bool> 외환계좌여부 { get; set; }
        public string 구분 { get; set; }
        public Nullable<bool> 사용여부 { get; set; }
        public Nullable<bool> 원천세확인 { get; set; }
        public string 주민번호 { get; set; }
        public string 용도 { get; set; }
        public Nullable<long> 분개거래처 { get; set; }
        public Nullable<short> 분개순번 { get; set; }
    }
}
