//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 인센티브일정요약
    {
        public long 견적번호 { get; set; }
        public short 일차 { get; set; }
        public string 숙박 { get; set; }
        public string 가이드 { get; set; }
        public string 식사 { get; set; }
        public string 조식 { get; set; }
        public string 중식 { get; set; }
        public string 석식 { get; set; }
        public string 현지교통 { get; set; }
        public string 자유시간 { get; set; }
        public string 비고 { get; set; }
    }
}
