//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 인센티브입찰
    {
        public long 입찰번호 { get; set; }
        public Nullable<System.DateTime> 견적일시작 { get; set; }
        public Nullable<System.DateTime> 견적마감일 { get; set; }
        public string 요청자구분 { get; set; }
        public Nullable<long> 개체번호 { get; set; }
        public string 요청자정보 { get; set; }
        public Nullable<short> 성인인원 { get; set; }
        public Nullable<short> 소아인원 { get; set; }
        public Nullable<short> 유아인원 { get; set; }
        public Nullable<short> 인솔자인원 { get; set; }
        public Nullable<short> 무료인원 { get; set; }
        public string 단체성격 { get; set; }
    }
}
