//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 인센티브추가항목
    {
        public long 추가요청번호 { get; set; }
        public long 단체번호 { get; set; }
        public Nullable<short> 순서 { get; set; }
        public string 항목구분1 { get; set; }
        public string 항목구분2 { get; set; }
        public string 요청상태 { get; set; }
        public string 비고 { get; set; }
    }
}
