//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 인센티브댓글
    {
        public long 인센댓글번호 { get; set; }
        public long 단체번호 { get; set; }
        public Nullable<short> 순서 { get; set; }
        public string 작성자구분 { get; set; }
        public Nullable<long> 작성자번호 { get; set; }
        public string 비고 { get; set; }
        public string 내용_내부 { get; set; }
    }
}
