//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 일정계획세부
    {
        public long 일정번호 { get; set; }
        public long 일정계획번호 { get; set; }
        public Nullable<System.DateTime> 날짜 { get; set; }
        public Nullable<short> 일차 { get; set; }
        public Nullable<short> 순서 { get; set; }
        public string 시간 { get; set; }
        public string 장소 { get; set; }
        public string 비고 { get; set; }
    }
}
