//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 장소이미지
    {
        public long 저작권파일번호 { get; set; }
        public Nullable<long> 저작권번호 { get; set; }
        public string 컨텐츠구분 { get; set; }
        public string 파일명 { get; set; }
        public string 파일경로 { get; set; }
        public Nullable<short> 가로해상도 { get; set; }
        public Nullable<short> 세로해상도 { get; set; }
        public long 파일크기 { get; set; }
        public string 키워드 { get; set; }
        public string 장소코드 { get; set; }
        public Nullable<long> 장소번호 { get; set; }
        public Nullable<long> 장소정보번호 { get; set; }
        public string 내용 { get; set; }
        public Nullable<bool> 저작권여부 { get; set; }
        public Nullable<short> 노출순서 { get; set; }
        public Nullable<bool> BFILE업로드여부 { get; set; }
        public Nullable<System.DateTime> BFILE업로드일자 { get; set; }
        public Nullable<bool> SFILE업로드여부 { get; set; }
        public Nullable<System.DateTime> SFILE업로드일자 { get; set; }
    }
}
