//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 장소
    {
        public string 장소코드 { get; set; }
        public string 국가코드 { get; set; }
        public string 도시코드 { get; set; }
        public Nullable<short> 순서 { get; set; }
        public string 장소분류코드 { get; set; }
        public string 장소명 { get; set; }
        public string 한글이름 { get; set; }
        public string 영문이름 { get; set; }
        public Nullable<long> 일정등록수 { get; set; }
        public Nullable<bool> 사용여부 { get; set; }
        public Nullable<long> 참조키 { get; set; }
        public string 구글키 { get; set; }
        public Nullable<long> 아이템번호 { get; set; }
        public string 카피라이팅 { get; set; }
        public string 장소설명 { get; set; }
        public string 강조사항 { get; set; }
        public Nullable<decimal> 숙박등급 { get; set; }
        public string 부대시설 { get; set; }
        public Nullable<double> 위도 { get; set; }
        public Nullable<double> 경도 { get; set; }
        public Nullable<decimal> 평점 { get; set; }
        public string 장소분류태그 { get; set; }
        public string 설명 { get; set; }
    }
}
