//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 저작권
    {
        public long 저작권번호 { get; set; }
        public string 저작권자분류 { get; set; }
        public Nullable<long> 저작권자 { get; set; }
        public string 저작권자명 { get; set; }
        public string 권한상태 { get; set; }
        public Nullable<System.DateTime> 권한보유일시작 { get; set; }
        public Nullable<System.DateTime> 권한보유일종료 { get; set; }
        public Nullable<short> 컨텐츠수 { get; set; }
        public string 파일명1 { get; set; }
        public string 파일명2 { get; set; }
        public string 파일명3 { get; set; }
        public string 파일명4 { get; set; }
        public string 파일명5 { get; set; }
        public string 파일명6 { get; set; }
    }
}
