//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 정산
    {
        public long 정산번호 { get; set; }
        public System.DateTime 정산기준일 { get; set; }
        public string 정산단위 { get; set; }
        public long 단체번호 { get; set; }
        public long 수익 { get; set; }
        public long 판매총액 { get; set; }
        public long 구매총액 { get; set; }
        public Nullable<bool> 분개여부 { get; set; }
        public Nullable<long> 분개번호 { get; set; }
    }
}
