//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 주문아이템
    {
        public long 주문아이템번호 { get; set; }
        public string 주문아이템코드 { get; set; }
        public string 품목코드 { get; set; }
        public string 공급처코드 { get; set; }
        public Nullable<System.DateTime> 주문일시 { get; set; }
        public Nullable<System.DateTime> 서비스시작일 { get; set; }
        public Nullable<System.DateTime> 서비스종료일 { get; set; }
        public string 주문상품명 { get; set; }
        public string 출발공항코드 { get; set; }
        public string 도착공항코드 { get; set; }
        public string 항공사코드 { get; set; }
        public string 여정구분 { get; set; }
        public Nullable<long> 아이템번호 { get; set; }
        public string 주문번호 { get; set; }
        public string 주문번호_공급처 { get; set; }
        public string 주문번호_판매처 { get; set; }
        public string 통화코드 { get; set; }
        public long 단가 { get; set; }
        public decimal 환율 { get; set; }
        public Nullable<short> 수량 { get; set; }
        public long 판매가격 { get; set; }
        public long 추가요금 { get; set; }
        public string 할인코드_모두 { get; set; }
        public string 할인코드_판매처 { get; set; }
        public string 예약자요청사항 { get; set; }
        public string 배송정보 { get; set; }
        public Nullable<System.DateTime> 마감일시_내부 { get; set; }
        public Nullable<System.DateTime> 마감일시_공급 { get; set; }
        public Nullable<bool> 증빙필요여부 { get; set; }
        public Nullable<System.DateTime> 마감일시_증빙 { get; set; }
        public string 상태코드 { get; set; }
        public Nullable<System.DateTime> 상태변경일시 { get; set; }
        public Nullable<long> 상태변경자 { get; set; }
        public Nullable<bool> 취소여부 { get; set; }
    }
}
