//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 지방
    {
        public string 국가코드 { get; set; }
        public string 지방코드 { get; set; }
        public string 지방구분 { get; set; }
        public string 지방명 { get; set; }
        public string 한글이름 { get; set; }
    }
}
