//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 지상비입찰시즌
    {
        public long 입찰번호 { get; set; }
        public string 시즌코드 { get; set; }
        public System.DateTime 행사시작일 { get; set; }
        public System.DateTime 행사종료일 { get; set; }
    }
}
