//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 지상비입찰숙박변경
    {
        public long 입찰번호 { get; set; }
        public long 상품번호 { get; set; }
        public long 장소번호 { get; set; }
        public string 장소코드 { get; set; }
    }
}
