//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 지상비견적업체
    {
        public long 입찰번호 { get; set; }
        public long 공급업체번호 { get; set; }
        public Nullable<bool> 낙찰여부 { get; set; }
        public string 견적비고 { get; set; }
        public string 낙찰비고 { get; set; }
    }
}
