//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 지상비견적조정
    {
        public long 견적조정번호 { get; set; }
        public long 견적번호 { get; set; }
        public Nullable<System.DateTime> 행사일시작 { get; set; }
        public Nullable<System.DateTime> 행사일종료 { get; set; }
        public long 조정단가 { get; set; }
        public string 조정사유 { get; set; }
    }
}
