//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 카달로그
    {
        public long 카달로그번호 { get; set; }
        public string 카달로그명 { get; set; }
        public Nullable<short> 레벨 { get; set; }
        public long 상위번호 { get; set; }
    }
}
