//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 카드가맹
    {
        public string 가맹점번호 { get; set; }
        public string 상점아이디 { get; set; }
        public string 카드사코드 { get; set; }
        public string 카드사명 { get; set; }
        public decimal 카드수수료율 { get; set; }
        public Nullable<long> 분개거래처번호 { get; set; }
        public Nullable<short> 분개순번 { get; set; }
        public string 상태 { get; set; }
        public string 비고 { get; set; }
    }
}
