//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 캠페인
    {
        public long 캠페인번호 { get; set; }
        public string 타이틀 { get; set; }
        public string 페이지경로 { get; set; }
        public string UI형식 { get; set; }
        public string 대표이미지 { get; set; }
        public Nullable<System.DateTime> 노출일시작 { get; set; }
        public Nullable<System.DateTime> 노출일마지막 { get; set; }
    }
}
