//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 테스트0528
    {
        public string 코드 { get; set; }
        public Nullable<System.DateTime> 컬럼2 { get; set; }
        public Nullable<int> 컬럼3 { get; set; }
        public int 번호 { get; set; }
    }
}
