//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 통장입금
    {
        public long 통장거래번호 { get; set; }
        public Nullable<System.DateTime> 수납일 { get; set; }
        public long 계좌번호 { get; set; }
        public long 수납액 { get; set; }
        public long 수납잔액 { get; set; }
        public string 송금자명 { get; set; }
        public Nullable<System.DateTime> 거래일자 { get; set; }
        public string 거래비고 { get; set; }
    }
}
