//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 통화
    {
        public string 통화코드 { get; set; }
        public decimal 환율 { get; set; }
        public string 심볼 { get; set; }
        public string 통화명 { get; set; }
        public Nullable<bool> 사용여부 { get; set; }
    }
}
