//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 특선상품요약
    {
        public long 특선상품번호 { get; set; }
        public long 상품번호 { get; set; }
        public string 판매채널구분 { get; set; }
        public Nullable<long> 제휴그룹번호 { get; set; }
        public string 제휴그룹 { get; set; }
        public System.DateTime 출발일 { get; set; }
        public long 판매가최소 { get; set; }
        public long 판매가최대 { get; set; }
    }
}
