//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 특선상품
    {
        public long 특선상품번호 { get; set; }
        public Nullable<long> 관리자 { get; set; }
        public string 추천아이콘 { get; set; }
        public string 특가명 { get; set; }
        public string 제목 { get; set; }
        public string 부제목 { get; set; }
        public string 카테고리명 { get; set; }
        public string 태그 { get; set; }
        public string 상담연락처 { get; set; }
        public string 캠페인번호 { get; set; }
        public string 간략설명 { get; set; }
        public string 간략특전 { get; set; }
        public string 추천글 { get; set; }
        public string 설명 { get; set; }
        public string 특전 { get; set; }
        public string 포함 { get; set; }
        public string 불포함 { get; set; }
        public string 이미지경로 { get; set; }
        public string 동영상경로 { get; set; }
        public string 연관상품경로 { get; set; }
        public Nullable<System.DateTime> 등록기한 { get; set; }
        public Nullable<System.DateTime> 기준일 { get; set; }
        public Nullable<System.DateTime> 마감일 { get; set; }
        public long 상품정상가 { get; set; }
        public decimal 할인율 { get; set; }
        public long 입찰시작가격 { get; set; }
        public Nullable<bool> 타임딜여부 { get; set; }
        public Nullable<bool> 비대면예약여부 { get; set; }
        public Nullable<bool> 연관상품노출여부 { get; set; }
        public Nullable<bool> 상품마감여부 { get; set; }
        public Nullable<bool> GL_활성여부 { get; set; }
        public Nullable<long> GL_목표모객 { get; set; }
        public long GL_VI { get; set; }
        public string GL_여행설명1 { get; set; }
        public string GL_여행설명2 { get; set; }
        public string GL_여행설명3 { get; set; }
    }
}
