//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 티켓
    {
        public string 티켓번호 { get; set; }
        public string 티켓구분 { get; set; }
        public string 항공코드번호 { get; set; }
        public string 티켓번호EX { get; set; }
        public Nullable<System.DateTime> 출발일 { get; set; }
        public long 판매명세번호 { get; set; }
        public Nullable<long> 주문번호 { get; set; }
        public Nullable<System.DateTime> 발권일 { get; set; }
        public Nullable<long> 발권자 { get; set; }
        public long FARE { get; set; }
        public long SHOWN { get; set; }
        public long DISC { get; set; }
        public long COMM { get; set; }
        public string FN { get; set; }
        public long CHARGE { get; set; }
        public long TAX { get; set; }
        public long QCHARGE { get; set; }
        public long CASH { get; set; }
        public long CARD { get; set; }
        public Nullable<bool> 분개여부 { get; set; }
        public Nullable<long> 분개번호 { get; set; }
        public Nullable<bool> 총액여부 { get; set; }
        public Nullable<bool> 자동발권여부 { get; set; }
        public string 비고 { get; set; }
    }
}
