//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 티켓재고
    {
        public string 티켓번호 { get; set; }
        public Nullable<System.DateTime> 입고일 { get; set; }
        public string 입고지코드 { get; set; }
        public Nullable<bool> 이티켓여부 { get; set; }
        public Nullable<bool> 국내선여부 { get; set; }
        public Nullable<long> 등록자 { get; set; }
        public Nullable<System.DateTime> 등록일 { get; set; }
    }
}
