//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 티켓_발권수수료
    {
        public long 발권수수료번호 { get; set; }
        public string 티켓번호 { get; set; }
        public string 구분 { get; set; }
        public string 항공코드번호 { get; set; }
        public Nullable<bool> ATR여부 { get; set; }
        public string GDS { get; set; }
        public long 발권수수료_CASH { get; set; }
        public long 발권수수료_CARD { get; set; }
        public string 카드번호 { get; set; }
        public Nullable<System.DateTime> 승인일 { get; set; }
        public string 승인번호 { get; set; }
        public string 비고 { get; set; }
        public Nullable<bool> 분개여부 { get; set; }
        public Nullable<long> 분개번호 { get; set; }
        public Nullable<long> 주문번호 { get; set; }
        public string 처리방식 { get; set; }
        public long 판매가격 { get; set; }
        public long 커미션_키인 { get; set; }
        public long 커미션부가세 { get; set; }
        public long 커미션원천세 { get; set; }
        public long 추가요금_수수료 { get; set; }
    }
}
