//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 티켓_발권수수료_은행입금
    {
        public Nullable<System.DateTime> 승인일 { get; set; }
        public string 승인번호 { get; set; }
        public long 승인금액 { get; set; }
        public long 결제수수료 { get; set; }
        public string 비고 { get; set; }
        public string TID { get; set; }
        public string 몰아이디 { get; set; }
        public string 카드계열 { get; set; }
        public string 무이자할부구분 { get; set; }
        public string 할부개월수 { get; set; }
        public Nullable<System.DateTime> 취소일 { get; set; }
        public Nullable<System.DateTime> 입금일 { get; set; }
        public long 카드수수료_공급가액 { get; set; }
        public long 카드수수료_부가세액 { get; set; }
        public Nullable<bool> 분개여부 { get; set; }
        public Nullable<long> 분개번호 { get; set; }
        public Nullable<long> 고객번호 { get; set; }
    }
}
