//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 판매가격세부
    {
        public long 주문가격세부번호 { get; set; }
        public long 고객번호 { get; set; }
        public string 참조구분 { get; set; }
        public long 참조번호 { get; set; }
        public string 항목명 { get; set; }
        public long 금액 { get; set; }
        public string 비고 { get; set; }
    }
}
