//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 판매주문외부연동로그
    {
        public long 외부연동로그번호 { get; set; }
        public Nullable<long> 외부연동번호 { get; set; }
        public string 서버명 { get; set; }
        public string 전송경로 { get; set; }
        public string 전송메소드 { get; set; }
        public string 전송데이터 { get; set; }
        public Nullable<System.DateTime> 전송일시 { get; set; }
        public Nullable<System.DateTime> 응답일시 { get; set; }
        public string 응답데이터 { get; set; }
        public Nullable<bool> 성공여부 { get; set; }
    }
}
