//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 판매업체세부
    {
        public long 거래처번호 { get; set; }
        public Nullable<bool> BP여부 { get; set; }
        public string BP거래처명 { get; set; }
        public Nullable<bool> 비즈전용여부 { get; set; }
        public Nullable<bool> 인센티브전용여부 { get; set; }
        public Nullable<bool> 으뜸BP여부 { get; set; }
        public string 여행업종류코드 { get; set; }
        public string 보증보험증권번호 { get; set; }
        public Nullable<System.DateTime> 만료일_지급보증 { get; set; }
        public Nullable<System.DateTime> 만료일_국외보험 { get; set; }
        public Nullable<System.DateTime> 만료일_국내보험 { get; set; }
        public string 통신판매업신고번호 { get; set; }
        public string 개인정보책임자 { get; set; }
        public string 파일경로_약도 { get; set; }
        public string 파일경로_로고 { get; set; }
        public string 지원품여부 { get; set; }
        public string 증빙확인여부 { get; set; }
        public string 상태 { get; set; }
    }
}
