//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 판매아이템
    {
        public long 판매번호 { get; set; }
        public Nullable<System.DateTime> 판매일시 { get; set; }
        public long 주문번호 { get; set; }
        public string 서비스주체 { get; set; }
        public string 품목구분 { get; set; }
        public string 품목종류 { get; set; }
        public Nullable<long> 상품번호 { get; set; }
        public Nullable<long> 단체번호 { get; set; }
        public Nullable<long> 가격번호 { get; set; }
        public string 공급처코드 { get; set; }
        public string 상품번호_공급처 { get; set; }
        public Nullable<System.DateTime> 행사시작일시 { get; set; }
        public Nullable<System.DateTime> 행사종료일시 { get; set; }
        public string 주문번호_공급처 { get; set; }
        public string 주문번호_판매처 { get; set; }
        public string 할인정보 { get; set; }
        public string 할인코드_판매처 { get; set; }
        public Nullable<System.DateTime> 마감일시_결제 { get; set; }
        public Nullable<System.DateTime> 마감일시_발권 { get; set; }
        public Nullable<bool> 증빙필요여부 { get; set; }
        public Nullable<bool> 비자필요여부 { get; set; }
        public string 예약자요청사항 { get; set; }
        public string 배송지정보 { get; set; }
        public Nullable<bool> 셀프수속희망여부 { get; set; }
        public string 예약경로 { get; set; }
        public Nullable<long> 웹사이트번호 { get; set; }
        public string 예약단말기 { get; set; }
        public Nullable<bool> 취소여부 { get; set; }
    }
}
