//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 판매주문외부연동
    {
        public long 외부연동번호 { get; set; }
        public string 품목코드 { get; set; }
        public string 구분 { get; set; }
        public string 주문번호_공급처 { get; set; }
        public string PNR2 { get; set; }
        public Nullable<long> 주문번호 { get; set; }
        public Nullable<long> 주문아이템번호 { get; set; }
        public Nullable<long> 결제요청번호 { get; set; }
        public Nullable<long> 발권요청번호 { get; set; }
        public string 판매처코드 { get; set; }
        public string 주문번호_판매처 { get; set; }
        public string 요청자 { get; set; }
        public Nullable<System.DateTime> 요청일시 { get; set; }
        public string 요청단말기 { get; set; }
        public string 요청구분 { get; set; }
        public string 요청데이터 { get; set; }
        public string 요청데이터2 { get; set; }
        public Nullable<short> 싱크횟수 { get; set; }
        public Nullable<bool> 싱크여부 { get; set; }
        public Nullable<System.DateTime> 싱크일시 { get; set; }
        public string 서버명 { get; set; }
        public Nullable<long> 사이트번호 { get; set; }
        public string 쿠키정보 { get; set; }
        public string 전문XML { get; set; }
    }
}
