//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 판매주문결제요청
    {
        public long 결제요청번호 { get; set; }
        public string 결제대상구분 { get; set; }
        public Nullable<long> 주문번호 { get; set; }
        public Nullable<long> 판매명세번호 { get; set; }
        public Nullable<long> 주문아이템번호 { get; set; }
        public Nullable<long> 작업요청번호 { get; set; }
        public string 대상자비고 { get; set; }
        public long 카드결제금액 { get; set; }
        public long 통장결제금액 { get; set; }
        public Nullable<bool> 카드결제여부 { get; set; }
        public string 카드사코드 { get; set; }
        public string 카드번호 { get; set; }
        public Nullable<bool> 법인카드여부 { get; set; }
        public string 소유자명 { get; set; }
        public string 관계 { get; set; }
        public string 연락처 { get; set; }
        public string 유효기간 { get; set; }
        public string 비밀번호 { get; set; }
        public Nullable<short> 할부기간 { get; set; }
        public Nullable<bool> 발권수수료여부 { get; set; }
        public long 수수료금액 { get; set; }
        public Nullable<short> 수수료할부기간 { get; set; }
        public string 수수료처리방식 { get; set; }
        public Nullable<long> 원천징수대상자 { get; set; }
        public string 인증결과 { get; set; }
        public Nullable<bool> 위험여부 { get; set; }
        public Nullable<bool> 확인여부 { get; set; }
        public Nullable<long> 확인자 { get; set; }
        public Nullable<bool> 통장결제여부 { get; set; }
        public Nullable<bool> 영수증신청여부 { get; set; }
        public string 영수증대상구분 { get; set; }
        public string 영수증신청번호 { get; set; }
    }
}
