//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 판매주문_배송
    {
        public long 주문번호 { get; set; }
        public string 수령인연락처 { get; set; }
        public Nullable<bool> 합배송여부 { get; set; }
        public string 수령인 { get; set; }
        public string 배송수단 { get; set; }
        public Nullable<System.DateTime> 배송예정일시 { get; set; }
        public string 배송지주소 { get; set; }
        public string 택배사코드 { get; set; }
        public string 운송장번호 { get; set; }
        public string 이티켓경로 { get; set; }
        public string 배송지구분 { get; set; }
        public string 배송상태 { get; set; }
        public long 배송비 { get; set; }
    }
}
