//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 판매주문
    {
        public long 주문번호 { get; set; }
        public string 주문경로 { get; set; }
        public string 예약자구분 { get; set; }
        public Nullable<long> 예약자번호 { get; set; }
        public string 한글성명 { get; set; }
        public string 이메일 { get; set; }
        public string 비밀번호 { get; set; }
        public Nullable<short> 출생년도 { get; set; }
        public Nullable<long> 판매거래처 { get; set; }
        public Nullable<long> 거래처직원 { get; set; }
        public Nullable<long> 판매부서 { get; set; }
        public Nullable<long> 판매파트 { get; set; }
        public Nullable<long> 판매담당자 { get; set; }
        public Nullable<long> 미수담당자 { get; set; }
        public Nullable<long> 운영부서 { get; set; }
        public Nullable<long> 운영파트 { get; set; }
        public Nullable<long> 운영담당자 { get; set; }
        public Nullable<System.DateTime> 주문일시 { get; set; }
        public Nullable<System.DateTime> 컨펌일시 { get; set; }
        public Nullable<System.DateTime> 완납일시 { get; set; }
        public Nullable<System.DateTime> 수정일시 { get; set; }
        public Nullable<System.DateTime> 미수유예일 { get; set; }
        public long 총주문액 { get; set; }
        public long 총부가세액 { get; set; }
        public Nullable<bool> 완납여부 { get; set; }
        public Nullable<bool> 업체결제여부 { get; set; }
        public long 총수납액 { get; set; }
        public long 총수납세액 { get; set; }
        public Nullable<System.DateTime> 계약동의일시 { get; set; }
        public Nullable<bool> 정산마감여부 { get; set; }
    }
}
