//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 판매주문작업메모
    {
        public long 작업메모번호 { get; set; }
        public long 작업요청번호 { get; set; }
        public Nullable<System.DateTime> 작성일시 { get; set; }
        public Nullable<long> 작성자 { get; set; }
        public string 메모 { get; set; }
        public string 요청구분 { get; set; }
        public string 작업상태코드 { get; set; }
    }
}
