//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 판매커미션정책
    {
        public long 정책번호 { get; set; }
        public Nullable<System.DateTime> 출발일시작 { get; set; }
        public Nullable<System.DateTime> 출발일종료 { get; set; }
        public string 가격채널 { get; set; }
        public string 판매채널 { get; set; }
        public Nullable<long> 거래처번호 { get; set; }
        public Nullable<bool> 고정커미션여부 { get; set; }
        public decimal 판매커미션율 { get; set; }
        public decimal 상품커미션율최소 { get; set; }
        public decimal 상품커미션율최대 { get; set; }
        public decimal 제휴할인율 { get; set; }
    }
}
