//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 판매제휴그룹
    {
        public long 제휴그룹번호 { get; set; }
        public string 제휴그룹명 { get; set; }
        public string 제휴그룹 { get; set; }
        public Nullable<short> 거래처수 { get; set; }
    }
}
