//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 판매수납
    {
        public long 판매수납번호 { get; set; }
        public long 주문번호 { get; set; }
        public string 수납종류 { get; set; }
        public Nullable<System.DateTime> 수납일 { get; set; }
        public Nullable<long> 거래처번호 { get; set; }
        public long 수납액 { get; set; }
        public long 공급가액 { get; set; }
        public long 부가세액 { get; set; }
        public string 비고 { get; set; }
        public Nullable<bool> 분개여부 { get; set; }
        public Nullable<long> 분개번호 { get; set; }
        public Nullable<long> 참조번호 { get; set; }
    }
}
