//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 판매고객
    {
        public long 판매명세번호 { get; set; }
        public string 여권번호 { get; set; }
        public Nullable<System.DateTime> 여권만료일 { get; set; }
        public string 여권발행국 { get; set; }
        public string 국적 { get; set; }
        public string 여권파일경로 { get; set; }
        public Nullable<System.DateTime> 생일 { get; set; }
        public string 이메일 { get; set; }
        public string 전화 { get; set; }
        public string ENC_여권번호 { get; set; }
        public string ENC_전화 { get; set; }
        public string ENC_이메일 { get; set; }
    }
}
