//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 판매주문작업요청
    {
        public long 작업요청번호 { get; set; }
        public Nullable<System.DateTime> 요청일시 { get; set; }
        public string 작업구분 { get; set; }
        public string 요청자구분 { get; set; }
        public Nullable<long> 요청자 { get; set; }
        public Nullable<long> 소속개체번호 { get; set; }
        public Nullable<bool> 해외요청여부 { get; set; }
        public string CRS구분 { get; set; }
        public string 주문번호_공급처 { get; set; }
        public Nullable<long> 주문아이템번호 { get; set; }
        public string PNRCOPY { get; set; }
        public string 주문번호 { get; set; }
        public string 요청상태 { get; set; }
        public Nullable<bool> 운임키인여부 { get; set; }
        public Nullable<bool> 증빙첨부여부 { get; set; }
        public Nullable<bool> 결제입력여부 { get; set; }
        public string 요청비고 { get; set; }
        public string 작업상태 { get; set; }
        public string 작업상태코드 { get; set; }
        public string 작업비고 { get; set; }
        public Nullable<System.DateTime> 상태변경일시 { get; set; }
        public Nullable<long> 상태변경자 { get; set; }
    }
}
