//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 판매커미션
    {
        public long 거래처번호 { get; set; }
        public string 상품종류 { get; set; }
        public System.DateTime 계약일시작 { get; set; }
        public System.DateTime 계약일종료 { get; set; }
        public decimal 상품커미션율 { get; set; }
        public decimal 제휴커미션율 { get; set; }
        public Nullable<bool> 총액여부 { get; set; }
    }
}
