//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 판매세부
    {
        public long 판매세부번호 { get; set; }
        public long 판매명세번호 { get; set; }
        public string 참조구분 { get; set; }
        public Nullable<long> 참조번호 { get; set; }
        public Nullable<bool> 영공반영여부 { get; set; }
        public string 항목명 { get; set; }
        public long 금액 { get; set; }
        public string 비고 { get; set; }
        public Nullable<long> 참조키 { get; set; }
    }
}
