//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 프로그램
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 프로그램()
        {
            this.프로그램권한 = new HashSet<프로그램권한>();
        }
    
        public int 프로그램번호 { get; set; }
        public string 프로그램명 { get; set; }
        public string 프로그램캡션 { get; set; }
        public Nullable<int> 상위프로그램번호 { get; set; }
        public bool 운영여부 { get; set; }
        public string 기능설명 { get; set; }
        public int 최초개발담당자 { get; set; }
        public int 개발담당자 { get; set; }
        public Nullable<int> 현업담당자 { get; set; }
        public Nullable<int> 첨부파일번호1 { get; set; }
        public Nullable<int> 첨부파일번호2 { get; set; }
        public string 비고 { get; set; }
        public System.DateTime 저장일시 { get; set; }
        public int 저장자 { get; set; }
        public string 저장년월 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<프로그램권한> 프로그램권한 { get; set; }
    }
}
