//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 프로모션
    {
        public long 프로모션번호 { get; set; }
        public string 프로모션명 { get; set; }
        public string 프로모션코드 { get; set; }
        public string 구분 { get; set; }
        public Nullable<System.DateTime> 행사일시작 { get; set; }
        public Nullable<System.DateTime> 행사일종료 { get; set; }
        public Nullable<System.DateTime> 주문일시작 { get; set; }
        public Nullable<System.DateTime> 주문일종료 { get; set; }
        public Nullable<short> 최소몇일전 { get; set; }
        public Nullable<short> 최대몇일전 { get; set; }
        public long 최소판매가격 { get; set; }
        public long 최소판매총액 { get; set; }
        public Nullable<bool> 신청금여부 { get; set; }
        public Nullable<short> 최소판매수량 { get; set; }
        public Nullable<short> 최대판매수량 { get; set; }
        public Nullable<short> 최대할인수량 { get; set; }
        public Nullable<bool> 소아집계여부 { get; set; }
        public Nullable<bool> 성인할인여부 { get; set; }
        public decimal 할인요율 { get; set; }
        public Nullable<bool> 할인한도여부 { get; set; }
        public long 할인한도금액 { get; set; }
        public Nullable<bool> 중복적용여부 { get; set; }
        public string 참조키 { get; set; }
    }
}
