//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 프로젝트플랜
    {
        public int 플랜번호 { get; set; }
        public string 업무분류코드 { get; set; }
        public string 프로젝트구분코드 { get; set; }
        public Nullable<int> 상위플랜번호 { get; set; }
        public string 플랜명 { get; set; }
        public string 프로젝트코드 { get; set; }
        public string 설명 { get; set; }
        public System.DateTime 요청일 { get; set; }
        public int 요청자 { get; set; }
        public Nullable<System.DateTime> 시작일 { get; set; }
        public Nullable<System.DateTime> 완료예정일 { get; set; }
        public Nullable<System.DateTime> 완료일 { get; set; }
        public Nullable<int> 개발담당자 { get; set; }
        public System.DateTime 저장일시 { get; set; }
        public int 저장자 { get; set; }
    }
}
