//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 필드
    {
        public long 필드번호 { get; set; }
        public string 참조구분 { get; set; }
        public string 필드구분 { get; set; }
        public string 필드명 { get; set; }
        public string 데이터타입 { get; set; }
        public string 필드값리스트 { get; set; }
        public Nullable<bool> 입력허용여부 { get; set; }
        public Nullable<bool> 필수입력여부 { get; set; }
    }
}
