//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 항공사
    {
        public string 대표항공코드 { get; set; }
        public string 항공코드 { get; set; }
        public string 항공사번호 { get; set; }
        public string 구분 { get; set; }
        public string 항공사명 { get; set; }
        public string 한글명 { get; set; }
        public string 영문명 { get; set; }
        public string 로고경로 { get; set; }
        public Nullable<long> 분개거래처번호 { get; set; }
    }
}
