//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 행사단체일정
    {
        public long 일정일련번호 { get; set; }
        public long 단체번호 { get; set; }
        public System.DateTime 날짜 { get; set; }
        public short 일차 { get; set; }
        public short 순서 { get; set; }
        public string 서비스종류 { get; set; }
        public Nullable<long> 장소번호 { get; set; }
        public string 장소비고 { get; set; }
        public string 장소코드 { get; set; }
    }
}
