//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 행사담당
    {
        public long 단체번호 { get; set; }
        public short 일차 { get; set; }
        public string 담당역할 { get; set; }
        public long 담당업체 { get; set; }
        public long 담당사원 { get; set; }
    }
}
