//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 회계분개
    {
        public long 분개번호 { get; set; }
        public string 분개종류 { get; set; }
        public Nullable<System.DateTime> 분개일시 { get; set; }
        public Nullable<long> 분개자 { get; set; }
    }
}
