//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 회계계정
    {
        public string 계정코드 { get; set; }
        public string 계정과목 { get; set; }
        public string 계정과목2 { get; set; }
        public string 구분 { get; set; }
        public Nullable<bool> 대표계정여부 { get; set; }
        public string 대차 { get; set; }
        public string IFRS코드 { get; set; }
        public string 분류1 { get; set; }
        public string 분류2 { get; set; }
        public string 분류3 { get; set; }
        public string 분류4 { get; set; }
        public string 대분류명 { get; set; }
        public string 중분류명 { get; set; }
        public string 소분류명 { get; set; }
        public Nullable<short> 대분류순서 { get; set; }
        public Nullable<short> 중분류순서 { get; set; }
        public Nullable<short> 소분류순서 { get; set; }
    }
}
