//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 회계이월
    {
        public long 이월번호 { get; set; }
        public string 회계년도 { get; set; }
        public string 계정코드 { get; set; }
        public Nullable<long> 거래처번호 { get; set; }
        public long 차변금액 { get; set; }
        public long 대변금액 { get; set; }
        public Nullable<long> 단체번호 { get; set; }
        public Nullable<long> 주문번호 { get; set; }
        public Nullable<long> 판매주문번호 { get; set; }
        public Nullable<long> 담당사원 { get; set; }
        public Nullable<long> 연결번호 { get; set; }
    }
}
