//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 회계전표
    {
        public long 전표번호 { get; set; }
        public System.DateTime 발행일 { get; set; }
        public short 순번 { get; set; }
        public string 대차 { get; set; }
        public string 계정코드 { get; set; }
        public long 거래처번호 { get; set; }
        public long 금액 { get; set; }
        public string 비고 { get; set; }
        public Nullable<long> 분개번호 { get; set; }
        public Nullable<long> 연결번호 { get; set; }
        public Nullable<long> 단체번호 { get; set; }
        public Nullable<long> 주문번호 { get; set; }
        public Nullable<long> 판매번호 { get; set; }
        public Nullable<long> 담당사원 { get; set; }
        public System.DateTime 등록일시 { get; set; }
        public long 등록자 { get; set; }
        public Nullable<System.DateTime> 수정일시 { get; set; }
        public Nullable<long> 수정자 { get; set; }
    }
}
