//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 회원활동이력
    {
        public long 활동이력번호 { get; set; }
        public long 회원번호 { get; set; }
        public System.DateTime 이력일시 { get; set; }
        public string 유입출처 { get; set; }
        public Nullable<long> 발송번호 { get; set; }
        public string 활동단계 { get; set; }
        public string 랜딩경로 { get; set; }
        public string 참조대상 { get; set; }
        public Nullable<long> 참조번호 { get; set; }
        public Nullable<bool> 공유여부 { get; set; }
        public string 공유문구 { get; set; }
        public string 활동구분 { get; set; }
    }
}
