//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6.EntityLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 회원
    {
        public long 회원번호 { get; set; }
        public string 한글성명 { get; set; }
        public string 영문성명 { get; set; }
        public string 영문성 { get; set; }
        public string 중간이름 { get; set; }
        public string 영문이름 { get; set; }
        public Nullable<System.DateTime> 생일 { get; set; }
        public string 성별 { get; set; }
        public string 가입경로 { get; set; }
        public string 아이디 { get; set; }
        public string 비밀번호 { get; set; }
        public string 프로필사진 { get; set; }
        public string 닉네임 { get; set; }
        public string CI { get; set; }
        public string 멤버쉽코드 { get; set; }
        public Nullable<bool> 외국인여부 { get; set; }
        public string 회원상태 { get; set; }
        public Nullable<System.DateTime> 가입일시 { get; set; }
        public Nullable<System.DateTime> 상태변경일시 { get; set; }
        public string 마케팅동의 { get; set; }
        public Nullable<System.DateTime> 마케팅변경일시 { get; set; }
        public Nullable<long> 파트너여행사 { get; set; }
    }
}
